version: '3'
services:
  app:
    image: my-node-app
    container_name: organizationAPI
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/organizationAPI
      JWT_SECRET: SECRET
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
